build:
    dependencies:
        before:
            - sudo composer self-update && composer --version
            - composer global require "fxp/composer-asset-plugin:1.0.0-beta3"
    environment:
        php:
            version: 5.5.12
    tests:
            override:
                - phpunit
checks:
    php:
        code_rating: true
        duplication: true
tools:
    php_sim: true
    php_pdepend: true
    php_analyzer: true
    external_code_coverage: true
filter:
    excluded_paths:
        - tests/*